# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Lyca
tagline:          'A blog'
description:      ''
url:              https://lyca0.github.io/
baseurl:          /

author:
  name:           'Lyca'
  url:            https://twitter.com/Lycalop

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://twitter.com/Lycalop
